-- Seed products (mirrors content/products.ts). Safe to re-run.
insert into products (slug, name, subtitle, price, size, count, tint, goal, short, long, features, usage, warnings, in_stock, best_seller, sort) values
('magnesium-complex', 'Magnesium', 'Complex', 14500, '60 capsules', 60, 'lavender', 'sleep',
 'Chelated magnesium for restful sleep and relaxed muscles.',
 'A gentle, chelated form of magnesium that is easy on the stomach. Take it in the evening as part of your wind-down routine after long days and longer commutes.',
 array['Magnesium bisglycinate','Gentle on the stomach','Vegetarian capsules'],
 'Take 2 capsules daily with water, ideally in the evening.',
 'Do not exceed the stated dose. Food supplements should not replace a varied diet. Consult your doctor if pregnant, breastfeeding or on medication.',
 true, true, 1),
('multivitamin', 'Multivitamin', '13 Essential Vitamins', 16000, '60 capsules', 60, 'peach', 'energy',
 'Thirteen essential vitamins for everyday energy.',
 'One daily capsule covering 13 essential vitamins, including B-complex for energy and vitamin D for days spent indoors at work.',
 array['Vitamins A, C, D3, E, K2','Full B-complex','Once daily'],
 'Take 1 capsule daily with breakfast.',
 'Do not exceed the stated dose. Keep out of reach of children. Consult your doctor if pregnant, breastfeeding or on medication.',
 true, true, 2),
('glucosamine', 'Glucosamine', 'MSM and Turmeric', 18500, '90 capsules', 90, 'sky', 'joints',
 'Glucosamine with MSM and turmeric for active joints.',
 'Glucosamine paired with MSM and turmeric, for people who stay on their feet, whether that''s the gym, the market or the football pitch.',
 array['Glucosamine sulphate','MSM','Turmeric extract'],
 'Take 3 capsules daily with food.',
 'Contains shellfish derivatives. Not suitable for people with shellfish allergy. Consult your doctor if on blood-thinning medication.',
 true, true, 3),
('niacinamide', 'Niacinamide', 'Marine Collagen and Hyaluronic Acid', 17000, '60 capsules', 60, 'mint', 'skin',
 'Vitamin B3 with marine collagen and hyaluronic acid for skin.',
 'Niacinamide (vitamin B3) with marine collagen and hyaluronic acid. A daily skin routine that works from the inside, in heat and harmattan alike.',
 array['Niacinamide (vitamin B3)','Marine collagen','Hyaluronic acid'],
 'Take 2 capsules daily with water.',
 'Contains fish. Do not exceed the stated dose. Consult your doctor if pregnant or breastfeeding.',
 true, true, 4),
('probiotic-complex', 'Probiotic', 'Complex', 19500, '30 capsules', 30, 'blush', 'gut',
 'Lactobacillus blend for everyday gut health.',
 'A multi-strain lactobacillus blend in delayed-release capsules, made to support your gut through every kind of meal.',
 array['Multi-strain lactobacillus','Delayed-release capsules','No refrigeration needed'],
 'Take 1 capsule daily before breakfast.',
 'Store below 25°C, away from direct sunlight. Consult your doctor if immunocompromised.',
 true, false, 5),
('vitamin-c-zinc', 'Vitamin C', 'Zinc and Elderberry', 12000, '60 capsules', 60, 'sun', 'immunity',
 'Vitamin C, zinc and elderberry for immune support.',
 'Vitamin C as ascorbic acid with zinc and elderberry. A simple daily habit for rainy season and every season.',
 array['Vitamin C (ascorbic acid)','Zinc','Elderberry extract'],
 'Take 1 capsule daily with food.',
 'Do not exceed the stated dose. Consult your doctor if pregnant, breastfeeding or on medication.',
 false, false, 6)
on conflict (slug) do update set
  name = excluded.name, subtitle = excluded.subtitle, price = excluded.price, size = excluded.size,
  count = excluded.count, tint = excluded.tint, goal = excluded.goal, short = excluded.short,
  long = excluded.long, features = excluded.features, usage = excluded.usage, warnings = excluded.warnings,
  in_stock = excluded.in_stock, best_seller = excluded.best_seller, sort = excluded.sort;
