import type { Goal, Product } from "./types";

// Seed catalogue. When Supabase is configured, products are read from the `products`
// table instead (see supabase/seed.sql, which mirrors this file).
// [CLAIM — needs evidence] All "supports …" wording must be checked against NAFDAC
// approval and the evidence for each formula before launch.
export const products: Product[] = [
  {
    slug: "magnesium-complex",
    name: "Magnesium",
    subtitle: "Complex",
    price: 14500,
    size: "60 capsules",
    count: 60,
    tint: "lavender",
    goal: "sleep",
    short: "Chelated magnesium for restful sleep and relaxed muscles.",
    long: "A gentle, chelated form of magnesium that is easy on the stomach. Take it in the evening as part of your wind-down routine after long days and longer commutes.",
    features: ["Magnesium bisglycinate", "Gentle on the stomach", "Vegetarian capsules"],
    usage: "Take 2 capsules daily with water, ideally in the evening.",
    warnings: "Do not exceed the stated dose. Food supplements should not replace a varied diet. Consult your doctor if pregnant, breastfeeding or on medication.",
    inStock: true,
    bestSeller: true,
  },
  {
    slug: "multivitamin",
    name: "Multivitamin",
    subtitle: "13 Essential Vitamins",
    price: 16000,
    size: "60 capsules",
    count: 60,
    tint: "peach",
    goal: "energy",
    short: "Thirteen essential vitamins for everyday energy.",
    long: "One daily capsule covering 13 essential vitamins, including B-complex for energy and vitamin D for days spent indoors at work.",
    features: ["Vitamins A, C, D3, E, K2", "Full B-complex", "Once daily"],
    usage: "Take 1 capsule daily with breakfast.",
    warnings: "Do not exceed the stated dose. Keep out of reach of children. Consult your doctor if pregnant, breastfeeding or on medication.",
    inStock: true,
    bestSeller: true,
  },
  {
    slug: "glucosamine",
    name: "Glucosamine",
    subtitle: "MSM and Turmeric",
    price: 18500,
    size: "90 capsules",
    count: 90,
    tint: "sky",
    goal: "joints",
    short: "Glucosamine with MSM and turmeric for active joints.",
    long: "Glucosamine paired with MSM and turmeric, for people who stay on their feet, whether that's the gym, the market or the football pitch.",
    features: ["Glucosamine sulphate", "MSM", "Turmeric extract"],
    usage: "Take 3 capsules daily with food.",
    warnings: "Contains shellfish derivatives. Not suitable for people with shellfish allergy. Consult your doctor if on blood-thinning medication.",
    inStock: true,
    bestSeller: true,
  },
  {
    slug: "niacinamide",
    name: "Niacinamide",
    subtitle: "Marine Collagen and Hyaluronic Acid",
    price: 17000,
    size: "60 capsules",
    count: 60,
    tint: "mint",
    goal: "skin",
    short: "Vitamin B3 with marine collagen and hyaluronic acid for skin.",
    long: "Niacinamide (vitamin B3) with marine collagen and hyaluronic acid. A daily skin routine that works from the inside, in heat and harmattan alike.",
    features: ["Niacinamide (vitamin B3)", "Marine collagen", "Hyaluronic acid"],
    usage: "Take 2 capsules daily with water.",
    warnings: "Contains fish. Do not exceed the stated dose. Consult your doctor if pregnant or breastfeeding.",
    inStock: true,
    bestSeller: true,
  },
  {
    slug: "probiotic-complex",
    name: "Probiotic",
    subtitle: "Complex",
    price: 19500,
    size: "30 capsules",
    count: 30,
    tint: "blush",
    goal: "gut",
    short: "Lactobacillus blend for everyday gut health.",
    long: "A multi-strain lactobacillus blend in delayed-release capsules, made to support your gut through every kind of meal.",
    features: ["Multi-strain lactobacillus", "Delayed-release capsules", "No refrigeration needed"],
    usage: "Take 1 capsule daily before breakfast.",
    warnings: "Store below 25°C, away from direct sunlight. Consult your doctor if immunocompromised.",
    inStock: true,
  },
  {
    slug: "vitamin-c-zinc",
    name: "Vitamin C",
    subtitle: "Zinc and Elderberry",
    price: 12000,
    size: "60 capsules",
    count: 60,
    tint: "sun",
    goal: "immunity",
    short: "Vitamin C, zinc and elderberry for immune support.",
    long: "Vitamin C as ascorbic acid with zinc and elderberry. A simple daily habit for rainy season and every season.",
    features: ["Vitamin C (ascorbic acid)", "Zinc", "Elderberry extract"],
    usage: "Take 1 capsule daily with food.",
    warnings: "Do not exceed the stated dose. Consult your doctor if pregnant, breastfeeding or on medication.",
    inStock: false,
  },
];

export const goals: { id: Goal; label: string }[] = [
  { id: "energy", label: "Energy" },
  { id: "immunity", label: "Immunity" },
  { id: "joints", label: "Joints" },
  { id: "gut", label: "Gut health" },
  { id: "skin", label: "Skin" },
  { id: "sleep", label: "Sleep" },
];
